[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "functions" # The folder you created in step 2
  
[[redirects]]
  from = "/*" # Route requests from /* to your function
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true
